env:
  global:
    - PHARO_DEP_MGMT=ubuntu
    - PHARO_VM=vm
  matrix:
    - PHARO_IMAGE=30
    - PHARO_IMAGE=40

install:
  - sh ci/install-deps.sh
  - sh ci/install-pharo.sh

script:
  - ./pharo Pharo.image eval ci/script.st
